In [123]:
import numpy as np
from matplotlib import pyplot as plt
#import os
import pandas as pd
from sklearn.model_selection import train_test_split
#from numpy import genfromtxt
%matplotlib inline

In [124]:
pwd

'/home/sathviksetty/python_progs/ml'

In [125]:
#extracting data from csv file
USAhousing = pd.read_csv('USA_Housing.csv')
#print(USAhousing)
USAhousing.head()
#USAhousing.info()
#USAhousing.describe()
#USAhousing.columns

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [126]:
#only Avg. Area Income is used as train_set

X1 = USAhousing[['Avg. Area Income']]
X = X1.values
#X = USAhousing.iloc[:, :1].values
#print(X)

In [127]:
y1 = USAhousing[['Price']]
#y = USAhousing[: , -2:-1].values
y = y1.values
#print(y)

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

#print(X_test)
print(y_test)

[[ 710269.2139681 ]
 [1210826.77328181]
 [ 594816.93251989]
 [1553311.16067977]
 [1056518.91326635]
 [1641749.65120549]
 [ 675536.39148857]
 [1100632.39113982]
 [1480328.34547335]
 [1325819.91310847]
 [1201785.6666718 ]
 [1557794.02127226]
 [ 992585.38232568]
 [ 578309.08618667]
 [1440909.00128311]
 [ 752168.06886998]
 [1148066.8130584 ]
 [ 729678.62621031]
 [1353488.41646297]
 [1389366.7180879 ]
 [ 647691.83520287]
 [1501917.31809565]
 [1375771.12903727]
 [1349818.25016203]
 [1222726.56436107]
 [1548962.88821738]
 [1484653.88407031]
 [1675062.89068713]
 [1181630.62516964]
 [1338247.93007436]
 [ 928538.78475622]
 [ 752842.67600168]
 [ 945614.56591276]
 [1186662.51422549]
 [ 785460.69766619]
 [1406437.68537389]
 [1762214.67958189]
 [1214262.69927372]
 [ 960904.99535186]
 [1689120.42652009]
 [ 758570.79719259]
 [1555490.62086308]
 [ 585440.43144771]
 [ 828497.06709607]
 [1693591.83537762]
 [1043281.2900747 ]
 [ 796666.12243218]
 [1408427.75841093]
 [1029855.71402412]
 [1244631.51935826]


In [129]:
from sklearn.preprocessing import StandardScaler
ScalerX = StandardScaler()
ScalerY = StandardScaler()

In [130]:
X_train = ScalerX.fit_transform(X_train)
y_train = ScalerY.fit_transform(y_train)
#print(X_train)
#print(y_train)

In [131]:
X_test = ScalerX.transform(X_test)
y_test = ScalerY.transform(y_test)

In [132]:
print(X_train.shape)
print(y_train.shape)
#print(X_train)
#print(X_test)

(4000, 1)
(4000, 1)


In [133]:
#w = np.random.rand(1)
#print(m)
#b = np.random.rand(1)
#print(b)

#print(h)

In [134]:
W = np.random.rand(1)
b = np.random.rand(1)
h = (X_train * W) + b
err = (y_train - h)
print(W)
print(b)
print(h.shape)
print(err.T)
print(X_train[:, 0])

[0.94200544]
[0.46145754]
(4000, 1)
[[-0.89326932 -0.33993273 -2.40082685 ...  0.3544414   1.44217101
   0.13739931]]
[-0.07522559  1.85898295  0.11229205 ... -0.2355306  -2.43340738
 -0.21976183]


In [135]:
def train(X, Y, lr = 0.05, epochs = 100):
    W = np.random.rand(1)
    b = np.random.rand(1)
    for e in range(epochs):
        h = np.dot(X , W) + b
        err = (Y - h)
        loss = np.mean(a = err**2)
        W[0] = W[0] - lr * (np.mean((X[:,0]) * err.T))
        
        b = b - lr * (np.mean(err))
        
        if e % 50 == 0:
            print("epochs: ",e, "loss: ",loss)
    return W, b        
            

In [136]:
W, b = train(X_train, y_train, lr = 0.01, epochs= 200)

epochs:  0 loss:  1.471701872514245
epochs:  50 loss:  1.2069839307034396
epochs:  100 loss:  1.247036486234974
epochs:  150 loss:  1.7589301339337664


In [137]:
W


array([-0.62434211])

In [138]:
b

array([1.34341232])

In [139]:
x_pred = np.array([80707.40491449])
x_pred_scale = ScalerX.transform(x_pred.reshape(1,-1))

In [140]:
y_pred = np.dot(x_pred_scale, W) + b

In [141]:
res = ScalerY.inverse_transform(y_pred)

In [142]:
res

array([1460786.28967251])

In [143]:
1102062.09757424

1102062.09757424