<a href="https://colab.research.google.com/github/SathvikSat/MachineLearning/blob/master/tensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x 

TensorFlow 2.x selected.


In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
print(tf.version)


<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [0]:
#tensor object
#tensor has datatype and a shape (dimension of tensor )

In [0]:
string = tf.Variable("This is a string", tf.string) #type and shape
number = tf.Variable(123, tf.int16)
floating = tf.Variable(1.2,  tf.float64)
#shape = 1 is scalar

In [0]:
#rank or degree - no dimesions above example rank is zero
#below is rank-1; array ie, deepet level of list 
rank_2tensor = tf.Variable([["test1", "test2", "test3"], ["hello1", "hello2", "Hello3" ]] , tf.string) #uniform num of elements in each dimensio, else err

In [37]:
tf.rank(rank_2tensor)
#numpy=# specifies rank, ie deepest level of list 

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [38]:
rank_2tensor.shape #how many itemms in each dimension 

TensorShape([2, 3])

In [53]:
#changing shape: 
#having same amount of elements in different shapes
tensor1  = tf.ones([1,2,3])
print(tensor1) #1 list, inside which 2 list each of 3 elements rank =3
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2) #2 list inside which 3 list, with each list of one element rank=3
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells tensor to cal the size of the dimension in that place 
# this will reshape the tensor to [3,2]
print(tensor3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [0]:
#types of tensors 1. Variable 3 mutable 
# other: Constants, placeholder, Sparse Tensor #these are immutable 